// biblia.js
const biblia = {
  "Genesis": {
    1: [
      "En el principio Dios creo los cielos y la tierra",
      "La tierra estaba sin orden y vacia, y las tinieblas cubrian la superficie del abismo, y el Espiritu de Dios se movia sobre la superficie de las aguas.",
      "Entonces dijo Dios: Sea la luz. Y hubo luz",
      "Dios vio que la luz era buena; y Dios separo la luz de las tinieblas.",
      "Y Dios llamo a la luz dia y a las tinieblas llamo noche. Y fue la tarde y fue la mañana: un día.",
      "Entonces dijo Dios: Haya expansion en medio de las aguas, y separe las aguas de las aguas.",
      "Dios hizo la expansion, y separo las aguas que estaban debajo de la expansion de las aguas que estaban sobre la expansion. Y asi fue.",
      "Y Dios llamo a la expansion cielos. Y fue la tarde y fue la mañana: el segundo dia.",
      "Entonces dijo Dios: Júntense en un lugar las aguas que estan debajo de los cielos, y que aparezca lo seco. Y así fue.",
      "Dios llamó a lo seco tierra, y al conjunto de las aguas llamó mares. Y Dios vio que era bueno.",
      "Entonces dijo Dios: Produzca la tierra vegetación: hierbas que den semilla, arboles frutales que den su fruto con su semilla sobre la tierra según su especie. Y así fue.",
      "Y produjo la tierra vegetación: hierbas que den semilla según su especie, y árboles que den su fruto con semilla, según su especie. Y Dios vio que era bueno.",
      "Y fue la tarde y fue la mañana: el tercer día",
      "Entonces dijo Dios: Haya lumbreras en la expansión de los cielos para separar el dia de la noche, y sean para señales y para estaciones y para dias y para años",
      "y sean por luminarias en la expansion de los cielos para alumbrar sobre la tierra. Y asi fue.",
      "Dios hizo las dos grandes lumbreras, la lumbrera mayor para dominio del día y la lumbrera menor para dominio de la noche. Hizo tambien las estrellas",
      "Dios las puso en la expansion de los cielos para alumbrar sobre la tierra,",
      "y para dominar el dia y la noche, y para separar la luz de las tinieblas. Y dios vio que era bueno.",
      "Y fue la tarde y fue la mañana: el cuarto día.",
      "Entonces dijo Dios: Llénense las aguas de multitudes de seres vivientes, y vuelen las aves sobre la tierra en la abierta expansión de los cielos.",
      "Y Dios creó los grandes monstruos marinos y todo ser viviente que se mueve, de los cuales, según su especie, están llenas las aguas, y toda ave según su especie. Y Dios vio que era bueno.",
      "Y dijo Dios: hagamos al hombre a Nuestra imagen, conforme a Nuestra semejanza; y ejerza dominio sobre los peces de mar, sobre las aves del cielo, sobre los ganados, sobre toda la tierra, y sobre todo reptil que se arrastra sobre la tierra.",
      "Dios creó al hombre a imagen Suya, a imagen de Dios lo creó; varón y hembra los creó.",
      "Dios los bendijo y les dijo: Sean fecundos y multipliquense. Llenen la tierra y sométanla. Ejerzan dominio sobre los peces de mar, sobre las aves del cielo y sobre todo ser viviente que se mueva sobre la tierra.",
      "También les dijo Dios: Miren, Yo les he dado a ustedes toda planta que da semilla que hay en la superficie de toda la tierra, y todo árbol que tiene fruto que da semilla; esto les servirá de alimento.",
      "Y a todo animal de la tierra, a toda ave de los cielos y a todo lo que se mueva sobre la tierra, y que tiene vida, les he dado toda planta verde para alimento. Y así fue.",
      "Dios vio todo lo que habia hecho; y era bueno en gran manera. Y fue la tarde y fue la mañana: el sexto día.",
    ],
    2: [
      "Así fueron acabados los cielos y la tierra y todas sus huestes.",
      "En el séptimo día ya Dios había completado la obra que había estado haciendo, y reposo en el día séptimo de toda la obra que había hecho.",
      "Dios bendijo al séptimo día y lo santificó, por que en él reposó de toda la obra que Él había creado y hecho.",
      "Estos son los orígenes de los cielos y de la tierra cuando fueron creados, el día en que el SEÑOR Dios hizo la tierra y los cielos.",
      "Aún no había ningún arbusto del campo en la tierra, ni había apun brotado ninguna planta del campo, por que el SEÑOR dios no había enviado lluvia sobre la tierra, ni había hombre para labrar la tierra.",
      "Pero se levantaba de la tierra un vapor que regaba toda la superficie del suelo.",
      "Entonces el SEÑOR Dios formó al hombre del polvo de la tierra, y sopló en su nariz el aliento de vida, y fue el hombre un ser viviente.",
      "Y el SEÑOR Dios plantó un huerto hacia el oriente, en Edén, y puso allí al hombre que habia formado.",
      "El SEÑOR Dios hizo brotar de la tierra todo árbol agradable a la vista y bueno para comer. Asimismo, en medio del huerto, hizo brotar el árbol de la vida y el árbol del conocimiento del bien y del mal.",
      "Del Edén salía un río para regar el huerto, y de alli se dividia y se convertía en otros cuatro ríos.",
      "El nombre del primero es Pisón. Este es el que rodea toda la tierra de Havila, donde hay oro.",
      "El oro de aquella tierra es bueno; allí hay bedelio y ónice.",
      "El nombre del segundo río es Gihón. Este es el que rodea la tierra de Cus.",
      "El nombre del tercer río es Tigris. Este es el que corre al oriente de Asiria. Y el cuarto río es el Éufrates.",
      "El SEÑOR Dios tomó al hombre y lo puso en el huerto del Edén para que lo cultivara y lo cuidara.",
      "Y el SEÑOR Dios ordenó al hombre: De todo árbol del huerto podrás comer,",
      "pero del árbol del conocimiento del bien y del mal no comerás, por que el día que de él comas, ciertamente morirás.",
      "Entonces el SEÑOR Dios dijo: Noes bueno que el hombre esté solo; le haré una ayuda adecuada.",
      "Y el SEÑOR Dios formó de la tierra todo animal del campo y toda ave del cielo, y los trajo al hombre para ver cómo los llamaría. Como el hombre llamó a cada ser viviente, ese fue su nombre.",
      "El hombre puso nombre a todo ganado y a las aves del cielo y a todo anomal del campo, pero para Adán no se encontró una ayuda que fuera adecuada para él.",
      "Entonces el SELOR Dios hizo caer un sueño profundo sobre el hombre, y este se durmió. Y Dios tomó una de sus costillas, y cerró la carne en ese lugar.",
      "De la costilla que el SEÑOR Dios había tomado del hombre, formó una mujer y la trajo al hombre.",
      "Y el hombre dijo: Esta es ahora hueso de mis huesos, y carne de mi carne. Ella será llamada mujer, Porque del hombre fue tomada.",
      "Por tanto el hombre dejará a su padre y a su madre y se unirá a su mujer, y serán una sola carne.",
      "Ambos estaban desnudos, el hombre y su mujer, pero no se avergonzaban.",
      "",
      "",
      "",
    ]
  }
};
