// biblia.js
const biblia = {
  "Genesis": {
    1: [
      "En el principio Dios creo los cielos y la tierra",
      "La tierra estaba sin orden y vacia, y las tinieblas cubrian la superficie del abismo, y el Espiritu de Dios se movia sobre la superficie de las aguas.",
      "Entonces dijo Dios: Sea la luz. Y hubo luz",
      "Dios vio que la luz era buena; y Dios separo la luz de las tinieblas.",
      "Y Dios llamo a la luz dia y a las tinieblas llamo noche. Y fue la tarde y fue la mañana: un día.",
      "Entonces dijo Dios: Haya expansion en medio de las aguas, y separe las aguas de las aguas.",
      "Dios hizo la expansion, y separo las aguas que estaban debajo de la expansion de las aguas que estaban sobre la expansion. Y asi fue.",
      "Y Dios llamo a la expansion cielos. Y fue la tarde y fue la mañana: el segundo dia.",
      "Entonces dijo Dios: Júntense en un lugar las aguas que estan debajo de los cielos, y que aparezca lo seco. Y así fue.",
      "Dios llamó a lo seco tierra, y al conjunto de las aguas llamó mares. Y Dios vio que era bueno.",
      "Entonces dijo Dios: Produzca la tierra vegetación: hierbas que den semilla, arboles frutales que den su fruto con su semilla sobre la tierra según su especie. Y así fue.",
      "Y produjo la tierra vegetación: hierbas que den semilla según su especie, y árboles que den su fruto con semilla, según su especie. Y Dios vio que era bueno.",
      "Y fue la tarde y fue la mañana: el tercer día",
      "Entonces dijo Dios: Haya lumbreras en la expansión de los cielos para separar el dia de la noche, y sean para señales y para estaciones y para dias y para años",
      "y sean por luminarias en la expansion de los cielos para alumbrar sobre la tierra. Y asi fue.",
      "Dios hizo las dos grandes lumbreras, la lumbrera mayor para dominio del día y la lumbrera menor para dominio de la noche. Hizo tambien las estrellas",
      "Dios las puso en la expansion de los cielos para alumbrar sobre la tierra,",
      "y para dominar el dia y la noche, y para separar la luz de las tinieblas. Y dios vio que era bueno.",
      "Y fue la tarde y fue la mañana: el cuarto día.",
      "Entonces dijo Dios: Llénense las aguas de multitudes de seres vivientes, y vuelen las aves sobre la tierra en la abierta expansión de los cielos.",
      "Y Dios creó los grandes monstruos marinos y todo ser viviente que se mueve, de los cuales, según su especie, están llenas las aguas, y toda ave según su especie. Y Dios vio que era bueno.",
      "Y dijo Dios: hagamos al hombre a Nuestra imagen, conforme a Nuestra semejanza; y ejerza dominio sobre los peces de mar, sobre las aves del cielo, sobre los ganados, sobre toda la tierra, y sobre todo reptil que se arrastra sobre la tierra.",
      "Dios creó al hombre a imagen Suya, a imagen de Dios lo creó; varón y hembra los creó.",
      "Dios los bendijo y les dijo: Sean fecundos y multipliquense. Llenen la tierra y sométanla. Ejerzan dominio sobre los peces de mar, sobre las aves del cielo y sobre todo ser viviente que se mueva sobre la tierra.",
      "También les dijo Dios: Miren, Yo les he dado a ustedes toda planta que da semilla que hay en la superficie de toda la tierra, y todo árbol que tiene fruto que da semilla; esto les servirá de alimento.",
      "Y a todo animal de la tierra, a toda ave de los cielos y a todo lo que se mueva sobre la tierra, y que tiene vida, les he dado toda planta verde para alimento. Y así fue.",
      "Dios vio todo lo que habia hecho; y era bueno en gran manera. Y fue la tarde y fue la mañana: el sexto día.",
    ],
    2: [
      "Así fueron acabados los cielos y la tierra y todas sus huestes.",
      "En el séptimo día ya Dios había completado la obra que había estado haciendo, y reposo en el día séptimo de toda la obra que había hecho.",
      "Dios bendijo al séptimo día y lo santificó, por que en él reposó de toda la obra que Él había creado y hecho.",
      "Estos son los orígenes de los cielos y de la tierra cuando fueron creados, el día en que el SEÑOR Dios hizo la tierra y los cielos.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ]
  }
};
